name: Purge CDN Cache
on: [push, workflow_dispatch]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install tencentcloud-sdk-python
      run: |
        pip install tencentcloud-sdk-python coscmd
    - name: Configure coscmd
      env: 
        secret_id: ${{ secrets.SecretId }}
        secret_key: ${{ secrets.SecretKey }}
        bucket: ${{ secrets.BUCKET }}
        region: ${{ secrets.REGION }}
      run: coscmd config -a $secret_id -s $secret_key -b $bucket -r $region
    - name: Upload to Tencent COS
      run: coscmd upload -rs --delete . /
    - name: Purge CDN Cache
      env:
          SecretId: ${{ secrets.SecretId }}
          SecretKey: ${{ secrets.SecretKey }}
      run: |
        python .github/cdn.py
